package bartbes:love-wasm@0.0.1;

interface keyboard
{
	enum key
	{
		unknown,
		return,
		escape,
		backspace,
		tab,
		space,
		exclaim,
		quotedbl,
		hash,
		percent,
		dollar,
		ampersand,
		quote,
		leftparen,
		rightparen,
		asterisk,
		plus,
		comma,
		minus,
		period,
		slash,
		zero,
		one,
		two,
		three,
		four,
		five,
		six,
		seven,
		eight,
		nine,
		colon,
		semicolon,
		less,
		equals,
		greater,
		question,
		at,
		leftbracket,
		backslash,
		rightbracket,
		caret,
		underscore,
		backquote,
		a,
		b,
		c,
		d,
		e,
		f,
		g,
		h,
		i,
		j,
		k,
		l,
		m,
		n,
		o,
		p,
		q,
		r,
		s,
		t,
		u,
		v,
		w,
		x,
		y,
		z,
		capslock,
		f1,
		f2,
		f3,
		f4,
		f5,
		f6,
		f7,
		f8,
		f9,
		f10,
		f11,
		f12,
		printscreen,
		scrolllock,
		pause,
		insert,
		home,
		pageup,
		delete,
		end,
		pagedown,
		right,
		left,
		down,
		up,
		numlockclear,
		kp-divide,
		kp-multiply,
		kp-minus,
		kp-plus,
		kp-enter,
		kp-one,
		kp-two,
		kp-three,
		kp-four,
		kp-five,
		kp-six,
		kp-seven,
		kp-eight,
		kp-nine,
		kp-zero,
		kp-period,
		kp-comma,
		kp-equals,
		application,
		power,
		f13,
		f14,
		f15,
		f16,
		f17,
		f18,
		f19,
		f20,
		f21,
		f22,
		f23,
		f24,
		execute,
		help,
		menu,
		select,
		stop,
		again,
		undo,
		cut,
		copy,
		paste,
		find,
		mute,
		volumeup,
		volumedown,
		alterase,
		sysreq,
		cancel,
		clear,
		prior,
		return2,
		separator,
		out,
		oper,
		clearagain,
		thousandsseparator,
		decimalseparator,
		currencyunit,
		currencysubunit,
		lctrl,
		lshift,
		lalt,
		lgui,
		rctrl,
		rshift,
		ralt,
		rgui,
		mode,
		audionext,
		audioprev,
		audiostop,
		audioplay,
		audiomute,
		mediaselect,
		www,
		mail,
		calculator,
		computer,
		app-search,
		app-home,
		app-back,
		app-forward,
		app-stop,
		app-refresh,
		app-bookmarks,
		brightnessdown,
		brightnessup,
		displayswitch,
		kbdillumtoggle,
		kbdillumdown,
		kbdillumup,
		eject,
		sleep,
	}

	//is-down: func(keys: list<key>) -> bool;
	is-down: func(key: key) -> bool;
}
